Preview bill page
DSC-MtA/unipay-mta pull request #32
Opened 2020-02-23 14:09 UTC by gzinck

Created a page for previewing a bill and selecting a tip amount.

![out](https://user-images.githubusercontent.com/39193440/75113439-60bc8380-5624-11ea-98bd-3f89ae8d307c.gif)

2020-02-29 00:31 UTC, syoon2 requested changes
Text cursor keeps moving to the last digit whenever a manual key is inputted...
Feels little uncomfortable if I try to manually decide the amount of tip

2020-02-29 17:41 UTC, gzinck commented
Turns out it was super buggy on web! I refactored it a bit to make manual entry easier. You can only edit it from the end, which is probably the fastest way of manually putting in a tip if you're trying to put it in really quickly. Also, I have not yet found a way to change the TextField text on the screen and move the cursor in one go without causing an infinite render loop in flutter 🤷‍♂️

2020-03-01 18:25 UTC, syoon2 approved these changes

2020-03-01 20:03 UTC, crystal-sharpe commented on lib/preview_bill/tip_selector.dart
> +                    color: Theme.of(context).primaryColor,
Suggestions:
- Add a "reset" or "0%" button to set the tip amount back to $0.00
- Rather than just have the "20%" option a `RaisedButton`, you could make whichever option was currently selected a `RaisedButton` and everything else a `FlatButton`
- Add a "Custom Amount" button to allow the user to enter a $ value (could open a pop-up window which verifies the amount is a valid amount)
- Add a "Custom %" button to allow the user to enter a custom % (could also open a pop-up window which verifies the percentage is between 0% and 100%)

2020-03-01 20:03 UTC, crystal-sharpe commented on lib/preview_bill/tip_selector.dart
> +                mainAxisAlignment: MainAxisAlignment.end,
The buttons which change the tip could be moved to the left side instead of the right so that the value of Tip Amount ($__.__) lines up with all the other costs without any interference with the buttons.

2020-03-01 20:03 UTC, crystal-sharpe commented on lib/preview_bill/tip_selector.dart
> +                    child: Text('Tip Amount'),
"Tip Amount" text could be bolded to make it consistent with "Subtotal" and "Total"

2023-10-23 19:03 UTC, closed without merging